"""
Thumbnail Upload Script for MataBumi

Uploads satellite thumbnail images from local outputs/thumbnails/ directory
to Supabase Storage bucket for production deployment.

This script is idempotent - it checks if files already exist before uploading
to avoid duplicates. It can be run multiple times safely.

Usage:
    python pipeline/upload_thumbnails.py

Environment Variables Required:
    SUPABASE_URL: Supabase project URL (e.g., https://xxx.supabase.co)
    SUPABASE_SERVICE_KEY: Supabase service role key (from Dashboard → Settings → API)

Example:
    export SUPABASE_URL=https://your-project.supabase.co
    export SUPABASE_SERVICE_KEY=your-service-role-key
    python pipeline/upload_thumbnails.py
"""

import os
import sys
from pathlib import Path
from typing import List, Tuple

try:
    from supabase import create_client, Client
except ImportError:
    print("❌ Error: supabase package not installed")
    print("   Install it with: pip install supabase>=2.0.0")
    sys.exit(1)


# Configuration
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_KEY")
BUCKET_NAME = "thumbnails"
THUMBNAILS_DIR = Path("outputs/thumbnails")


def validate_environment() -> None:
    """
    Validate that required environment variables are set.
    
    Raises:
        SystemExit: If environment variables are missing
    """
    if not SUPABASE_URL:
        print("❌ Error: SUPABASE_URL environment variable not set")
        print("   Set it with: export SUPABASE_URL=https://your-project.supabase.co")
        sys.exit(1)
    
    if not SUPABASE_KEY:
        print("❌ Error: SUPABASE_SERVICE_KEY environment variable not set")
        print("   Set it with: export SUPABASE_SERVICE_KEY=your-service-role-key")
        sys.exit(1)
    
    if not THUMBNAILS_DIR.exists():
        print(f"❌ Error: Thumbnails directory not found: {THUMBNAILS_DIR}")
        print("   Make sure you're running this script from the project root directory")
        sys.exit(1)


def get_thumbnail_files() -> List[Path]:
    """
    Get list of thumbnail files to upload.
    
    Returns:
        List of Path objects for .jpg files in thumbnails directory
    """
    thumbnails = list(THUMBNAILS_DIR.glob("*.jpg"))
    
    if not thumbnails:
        print(f"⚠️  Warning: No .jpg files found in {THUMBNAILS_DIR}")
        print("   Make sure thumbnails have been generated by the pipeline")
    
    return thumbnails


def check_file_exists(client: Client, filename: str) -> bool:
    """
    Check if a file already exists in the Supabase Storage bucket.
    
    Args:
        client: Supabase client instance
        filename: Name of the file to check
        
    Returns:
        True if file exists, False otherwise
    """
    try:
        # List files in bucket with the specific filename
        files = client.storage.from_(BUCKET_NAME).list(path="", search=filename)
        
        # Check if any file matches exactly
        for file in files:
            if file.get("name") == filename:
                return True
        
        return False
    except Exception as e:
        # If error occurs (e.g., bucket doesn't exist), assume file doesn't exist
        return False


def upload_file(client: Client, file_path: Path) -> Tuple[bool, str]:
    """
    Upload a single thumbnail file to Supabase Storage.
    
    Args:
        client: Supabase client instance
        file_path: Path to the thumbnail file
        
    Returns:
        Tuple of (success: bool, message: str)
    """
    filename = file_path.name
    
    try:
        # Check if file already exists (idempotent)
        if check_file_exists(client, filename):
            return True, f"✓ {filename} already exists, skipping"
        
        # Read file content
        with open(file_path, 'rb') as f:
            file_content = f.read()
        
        # Upload to Supabase Storage
        client.storage.from_(BUCKET_NAME).upload(
            path=filename,
            file=file_content,
            file_options={"content-type": "image/jpeg"}
        )
        
        return True, f"✓ Uploaded {filename}"
        
    except Exception as e:
        return False, f"✗ Failed to upload {filename}: {str(e)}"


def upload_thumbnails() -> None:
    """
    Main function to upload all thumbnails to Supabase Storage.
    
    This function:
    1. Validates environment variables
    2. Connects to Supabase
    3. Uploads all thumbnail files (skipping existing ones)
    4. Reports results
    """
    print("=" * 70)
    print("MataBumi Thumbnail Upload to Supabase Storage")
    print("=" * 70)
    print()
    
    # Validate environment
    validate_environment()
    
    # Get thumbnail files
    thumbnails = get_thumbnail_files()
    
    if not thumbnails:
        print("\n❌ No thumbnails to upload")
        return
    
    print(f"Found {len(thumbnails)} thumbnail(s) to process")
    print(f"Bucket: {BUCKET_NAME}")
    print(f"Supabase URL: {SUPABASE_URL}")
    print()
    
    # Create Supabase client
    try:
        client: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    except Exception as e:
        print(f"❌ Error: Failed to connect to Supabase: {e}")
        sys.exit(1)
    
    # Upload files
    success_count = 0
    skip_count = 0
    fail_count = 0
    
    for thumbnail_path in thumbnails:
        success, message = upload_file(client, thumbnail_path)
        print(message)
        
        if success:
            if "already exists" in message:
                skip_count += 1
            else:
                success_count += 1
        else:
            fail_count += 1
    
    # Print summary
    print()
    print("=" * 70)
    print("Upload Summary")
    print("=" * 70)
    print(f"✓ Successfully uploaded: {success_count}")
    print(f"⊘ Skipped (already exists): {skip_count}")
    print(f"✗ Failed: {fail_count}")
    print(f"Total processed: {len(thumbnails)}")
    print()
    
    if fail_count > 0:
        print("⚠️  Some uploads failed. Check error messages above.")
        sys.exit(1)
    else:
        print("✅ All thumbnails uploaded successfully!")
        print()
        print("Next steps:")
        print("1. Verify thumbnails in Supabase Dashboard → Storage → thumbnails")
        print("2. Test thumbnail URLs:")
        print(f"   {SUPABASE_URL}/storage/v1/object/public/{BUCKET_NAME}/[filename]")
        print("3. Deploy application to Vercel with SUPABASE_URL and SUPABASE_SERVICE_KEY")


if __name__ == "__main__":
    upload_thumbnails()
